theme: minima
title: DOBI TRADE
description: Global Cryptocurrency Trading Platform
show_downloads: false
layout: default 

twitter_username: dobitrade_
github_username: blockchainrdc2018
telegram_username: dobitrade.com

minima:
  date_format: ""